version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - movie-app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api-server
  api-server:
    image: api-server
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - movie-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  movie-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local